backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "users"
    label: "User Profiles"
    folder: "content/users/"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Username" }
      - { name: "bio", label: "Bio" }
      - { name: "avatar", label: "Avatar", widget: "image" }
      - { name: "discord", label: "Discord Handle" }

  - name: "posts"
    label: "Blog Posts"
    folder: "content/users/"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "tags", label: "Tags", widget: "list" }
      - { name: "author", label: "Author" }
      - { name: "body", label: "Body", widget: "markdown" }
